### ISSUE TITLE
Steps of replacing large files

### ISSUE THREAD

**Issue by johnnytam100** [kiharalab/DOVE#3]
Wang, thank you for the reply, let me make this reply open so others can see.

I have now performed the following:

Step1: clone DOVE
```
git clone https://github.rcac.purdue.edu/kiharalab/DOVE.git
```

Step2: download model files (due to large size, has to be downloaded separately from git clone)
```
wget http://kiharalab.org/dove/Large_LFSS.tar.gz
tar zxvf Large_LFSS.tar.gz
```

Step3: Replace files
```
rm -rf ./DOVE/Goap/
mv Large_LFS/Goap/ ./DOVE/
rm -rf ./DOVE/Best_Model/*
mv Large_LFS/* ./DOVE/Best_Model/
```

Then, I tested by:
```
cd DOVE
python main.py --mode 0 -F Example/Decoys/complex.1.pdb
```

```
2020-10-22 12:37:28.134594: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-10-22 12:37:28.134766: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/bwfefs/home/cltam/20200725_pose_prediction_neural_net/step7_benchmark_with_docking_methods/test_DOVE/DOVE_master/DOVE/Example/Decoys/complex.1888 existed
TER     838      ARG A 108

[error] encountered blank atom name
TER    1743      SER B 116

[error] encountered blank atom name
TER    1002      LEU C 129

[error] encountered blank atom name
ENDMDL

[error] encountered blank atom name
waiting dealing1
At line 110 of file goap.f (unit = 20, file = '▒▒▒^')
Fortran runtime error: File '/fort.21_1.61_2' does not exist
in total, we have 210 residues in receptor, 122 residues in ligand
in the interface 10A cut off, we have 95 residue, 826 atoms in the receptor
in the interface 10A cut off, we have 59 residue, 492 atoms in the ligand
after processing, we only remained 826 atoms in receptor, 492 atoms in ligand
209 atoms actually used in this receptor
/bwfefs/home/cltam/20200725_pose_prediction_neural_net/step7_benchmark_with_docking_methods/test_DOVE/DOVE_master/DOVE/data_processing/prepare_input.py:360: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if atom_type=='C' or atom_type=='CA':
/bwfefs/home/cltam/20200725_pose_prediction_neural_net/step7_benchmark_with_docking_methods/test_DOVE/DOVE_master/DOVE/data_processing/prepare_input.py:366: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif atom_type=='N':
/bwfefs/home/cltam/20200725_pose_prediction_neural_net/step7_benchmark_with_docking_methods/test_DOVE/DOVE_master/DOVE/data_processing/prepare_input.py:372: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif atom_type=='O':
350 atoms actually used in this example
C atom 50, N atom 25, O atom 25, other atom 250
in the interface 10A cut off, we have 95 residue, 826 atoms in the receptor
in the interface 10A cut off, we have 59 residue, 492 atoms in the ligand
after processing, we only remained 826 atoms in receptor, 492 atoms in ligand
690 atoms actually used in this receptor
1139 atoms actually used in this example
C atom 175, N atom 89, O atom 89, other atom 786
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    record,input_path=run_pred_single(file_path,random_id,gpu_id)
  File "main.py", line 16, in run_pred_single
    input_path=Prepare_Input_Singe(file_path,random_id)
  File "/bwfefs/home/cltam/20200725_pose_prediction_neural_net/step7_benchmark_with_docking_methods/test_DOVE/DOVE_master/DOVE/Input_Preparing/Prepare_Input_Single.py", line 54, in Prepare_Input_Singe
    rlist, llist = form_goap_list(work_decoy2, rcount)
  File "/bwfefs/home/cltam/20200725_pose_prediction_neural_net/step7_benchmark_with_docking_methods/test_DOVE/DOVE_master/DOVE/data_processing/prepare_goap_input.py", line 14, in form_goap_list
    with open(item,'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/bwfefs/home/cltam/20200725_pose_prediction_neural_net/step7_benchmark_with_docking_methods/test_DOVE/DOVE_master/DOVE/Example/Decoys/complex.1888/888_goap.pdb'
```

The output message changed, but still got the same error at last "FileNotFoundError: [Errno 2] No such file or directory: ..."

Do you have any idea how to proceed in such a case?

Sorry for the disturbance and thanks again!

**Comment by wang3702** [comment]
Sorry I did not see your new post before. I think you need to download goap. However, you failed to download it. I suggested you to download here: https://github.rcac.purdue.edu/kiharalab/DOVE/tree/master/Goap. This directory includes large files please make sure you successfully download it. Github will have downloading limit for each repo every month. I am not sure if my repo exceeds or not .

**Comment by wang3702** [comment]
Your error message: Fortran runtime error: File '/fort.21_1.61_2' does not exist
Please download it from my posted link before and put that into the Goap directory
