### ISSUE TITLE
Hi Wang

### ISSUE THREAD

**Issue by johnnytam100** [kiharalab/DOVE#8]
```
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    record,input_path=run_pred_single(file_path,random_id,gpu_id)
  File "main.py", line 16, in run_pred_single
    input_path=Prepare_Input_Singe(file_path,random_id)
  File "/ydcs/cltam/20210511_NbX_DOVE_complex-only_single2/1g6v_complex/Input_Preparing/Prepare_Input_Single.py", line 45, in Prepare_Input_Singe
    tempload, rlength, llength = reform_input(rlist, llist, 1)
  File "/ydcs/cltam/20210511_NbX_DOVE_complex-only_single2/1g6v_complex/data_processing/prepare_input.py", line 286, in reform_input
    xmean=np.mean(coordinate[:,0])
IndexError: too many indices for array
```

I am trying to use DOVE but met this message, do you know how to fix this one??

Thanks a lot!!!

**Comment by wang3702** [comment]
Thanks a lot for your interest in DOVE! I think this is because the interface extraction failed to extract the interface region. Could you please check your input followed the PDB format and the receptor with chain "A" and ligand with chain "B" in your input PDB? Any further questions, welcome to raise here.

**Comment by johnnytam100** [comment]
Thanks Wang!
